f = open("mi_archivo.txt","a")
f.write("este archivo es de prueba\n")
f.close()
f = open("mi_archivo.txt","r")
print(f.read())
f.close()
f = open("mi_archivo.txt", "a")
f.write("yeeey\n")
f.close()
f = open("mi_archivo.txt","r")
print(f.read())
f.close()